"""Report Generator with Evidence IDs (Phase 2).

Generates markdown reports with automatic Evidence ID references.
Each claim in the report is annotated with its supporting evidence IDs.
"""
from typing import List, Dict, Any
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate Phase 2 compliant reports with evidence annotations."""
    
    def __init__(self):
        self.evidence_by_claim = {}
    
    def _build_evidence_map(self, claims: List[Dict], evidence_list: List[Dict]) -> None:
        """Build mapping from claim_id to evidence IDs."""
        self.evidence_by_claim = {}
        
        for ev in evidence_list:
            claim_id = ev.get("claim_id")
            ev_id = ev.get("evidence_id")
            
            if claim_id and ev_id:
                if claim_id not in self.evidence_by_claim:
                    self.evidence_by_claim[claim_id] = []
                self.evidence_by_claim[claim_id].append({
                    "evidence_id": ev_id,
                    "paper_id": ev.get("paper_id"),
                    "strength": ev.get("evidence_strength", "Unknown"),
                    "quote": ev.get("quote_span", "")[:100]  # First 100 chars
                })
    
    def generate_claim_with_evidence(self, claim: Dict) -> str:
        """Generate claim text with evidence ID annotations.
        
        Args:
            claim: Claim dictionary with claim_id and claim_text
            
        Returns:
            Markdown text with evidence references
        """
        claim_id = claim.get("claim_id")
        claim_text = claim.get("claim_text", "")
        
        # Get supporting evidence
        evidence = self.evidence_by_claim.get(claim_id, [])
        
        if not evidence:
            # No evidence - mark as uncertain
            return f"> [!WARNING] **Unsupported Claim**\n> {claim_text}\n> \n> *No supporting evidence found.*\n"
        
        # Format with evidence IDs
        ev_refs = ", ".join([f"^{ev['evidence_id'][:8]}" for ev in evidence])
        
        # Build markdown
        md_lines = [
            f"{claim_text} [{ev_refs}]",
            ""
        ]
        
        # Add evidence details in note
        if len(evidence) <= 3:  # Only show details if few evidence
            md_lines.append("> [!NOTE] Evidence")
            for ev in evidence:
                paper_id = ev.get("paper_id", "Unknown")
                strength = ev.get("strength", "Unknown")
                md_lines.append(f"> - **{strength}**: {paper_id}")
                md_lines.append(f">   Quote: \"{ev.get('quote', '')[:80]}...\"")
            md_lines.append("")
        
        return "\n".join(md_lines)
    
    def generate_full_report(
        self,
        query: str,
        claims: List[Dict],
        evidence_list: List[Dict],
        papers: List[Dict],
        scores: Dict = None
    ) -> str:
        """Generate complete markdown report with evidence IDs.
        
        Args:
            query: Research question
            claims: List of claim dictionaries
            evidence_list: List of evidence dictionaries
            papers: List of paper dictionaries
            scores: Optional scoring information
            
        Returns:
            Complete markdown report
        """
        # Build evidence mapping
        self._build_evidence_map(claims, evidence_list)
        
        # Calculate statistics
        total_claims = len(claims)
        supported_claims = len([c for c in claims if c.get("claim_id") in self.evidence_by_claim])
        support_rate = supported_claims / total_claims if total_claims > 0 else 0.0
        
        # Start building report
        lines = [
            f"# Research Report: {query}",
            "",
            f"> Generated by JARVIS Research OS (Phase 2)",
            f"> Total Papers: {len(papers)} | Claims: {total_claims} | Support Rate: {support_rate:.1%}",
            "",
            "---",
            "",
        ]
        
        # Add quality warning if support rate is low
        if support_rate < 0.90:
            lines.extend([
                "> [!CAUTION] Low Evidence Support",
                f"> This report has a support rate of {support_rate:.1%}, below the recommended 90% threshold.",
                "> Please interpret findings with caution.",
                "",
            ])
        
        # Group claims by type
        claims_by_type = {}
        for claim in claims:
            claim_type = claim.get("claim_type", "Unknown")
            if claim_type not in claims_by_type:
                claims_by_type[claim_type] = []
            claims_by_type[claim_type].append(claim)
        
        # Generate sections
        for claim_type, type_claims in claims_by_type.items():
            if claim_type == "Unknown":
                continue
            
            lines.extend([
                f"## {claim_type}",
                "",
            ])
            
            for claim in type_claims:
                claim_md = self.generate_claim_with_evidence(claim)
                lines.append(claim_md)
            
            lines.append("")
        
        # Add unknown claims section if any
        unknown_claims = claims_by_type.get("Unknown", [])
        if unknown_claims:
            lines.extend([
                "## Other Findings",
                "",
            ])
            for claim in unknown_claims:
                claim_md = self.generate_claim_with_evidence(claim)
                lines.append(claim_md)
        
        # Add papers section
        lines.extend([
            "---",
            "",
            "## References",
            "",
        ])
        
        for paper in papers[:10]:  # Top 10 papers
            paper_id = paper.get("paper_id", "Unknown")
            title = paper.get("title", "Untitled")
            authors = paper.get("authors", ["Unknown"])
            year = paper.get("year", "N/A")
            
            author_str = ", ".join(authors[:3])
            if len(authors) > 3:
                author_str += " et al."
            
            lines.append(f"- **{paper_id}**: {author_str} ({year}). {title}")
        
        lines.append("")
        
        return "\n".join(lines)


def generate_report_with_evidence(
    query: str,
    claims: List[Dict],
    evidence: List[Dict],
    papers: List[Dict],
    scores: Dict = None
) -> str:
    """Convenience function to generate report.
    
    Args:
        query: Research question
        claims: List of claims
        evidence: List of evidence
        papers: List of papers
        scores: Optional scores
    
    Returns:
        Markdown report string
    """
    generator = ReportGenerator()
    return generator.generate_full_report(query, claims, evidence, papers, scores)
