openapi: 3.0.3
info:
  title: JARVIS API Contract v1
  version: v1
servers:
  - url: /
paths:
  /api/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /api/capabilities:
    get:
      summary: Capabilities
      responses:
        '200':
          description: OK
  /api/runs:
    get:
      summary: List runs
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: OK
  /api/runs/{run_id}:
    get:
      summary: Run detail
      parameters:
        - in: path
          name: run_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
  /api/runs/{run_id}/files:
    get:
      summary: List run files
      parameters:
        - in: path
          name: run_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /api/runs/{run_id}/files/{path}:
    get:
      summary: Download run file
      parameters:
        - in: path
          name: run_id
          required: true
          schema:
            type: string
        - in: path
          name: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File
        '400':
          description: Invalid path
        '404':
          description: Not found
  /api/runs/{run_id}/events:
    get:
      summary: Run events
      parameters:
        - in: path
          name: run_id
          required: true
          schema:
            type: string
      responses:
        '501':
          description: Not implemented
  /api/research/rank:
    get:
      summary: Research rank
      parameters:
        - in: query
          name: run_id
          required: true
          schema:
            type: string
        - in: query
          name: top_k
          schema:
            type: integer
        - in: query
          name: q
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
  /api/research/paper/{paper_id}:
    get:
      summary: Research paper
      parameters:
        - in: path
          name: paper_id
          required: true
          schema:
            type: string
        - in: query
          name: run_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
  /api/qa/report:
    get:
      summary: QA report
      parameters:
        - in: query
          name: run_id
          schema:
            type: string
      responses:
        '501':
          description: Not implemented
  /api/submission/build:
    post:
      summary: Build submission
      responses:
        '501':
          description: Not implemented
  /api/submission/run/{run_id}/latest:
    get:
      summary: Submission latest
      parameters:
        - in: path
          name: run_id
          required: true
          schema:
            type: string
      responses:
        '501':
          description: Not implemented
  /api/submission/run/{run_id}/changelog:
    get:
      summary: Submission changelog
      parameters:
        - in: path
          name: run_id
          required: true
          schema:
            type: string
        - in: query
          name: version
          required: true
          schema:
            type: string
      responses:
        '501':
          description: Not implemented
  /api/submission/run/{run_id}/email:
    get:
      summary: Submission email
      parameters:
        - in: path
          name: run_id
          required: true
          schema:
            type: string
        - in: query
          name: version
          required: true
          schema:
            type: string
        - in: query
          name: recipient_type
          required: true
          schema:
            type: string
      responses:
        '501':
          description: Not implemented
  /api/feedback/risk:
    get:
      summary: Feedback risk
      parameters:
        - in: query
          name: run_id
          schema:
            type: string
      responses:
        '501':
          description: Not implemented
  /api/feedback/import:
    post:
      summary: Feedback import
      responses:
        '501':
          description: Not implemented
  /api/decision/simulate:
    post:
      summary: Decision simulate
      responses:
        '501':
          description: Not implemented
  /api/finance/optimize:
    post:
      summary: Finance optimize
      responses:
        '200':
          description: OK
        '500':
          description: Error
