"""JARVIS Lab Automation Module Exports"""

from .automation import (
    AnomalyDetector,
    APIGateway,
    AuthorProfileBuilder,
    AutomatedPipetting,
    BayesianOptimizer,
    BrowserSessionManager,
    CellCultureMonitor,
    CitationAlertAgent,
    ConferenceTracker,
    CostTracker,
    CredentialVault,
    DataExtractionAgent,
    EnvironmentalMonitor,
    ErrorRecoveryAgent,
    ExperimentLogger,
    ExperimentScheduler,
    FlowCytometryAnalyzer,
    FormAutoFiller,
    GrantDeadlineTracker,
    InstitutionMapper,
    JobPostingMonitor,
    LabEquipmentController,
    LabSafetyMonitor,
    LoginManager,
    # MCP Tools
    MCPServerManager,
    MicroscopeController,
    NewsAggregator,
    PatentMonitor,
    PaywallHandler,
    PCROptimizer,
    PDFDownloader,
    PlateReaderIntegration,
    PreprintTracker,
    ProtocolVersionControl,
    QualityControlAgent,
    RateLimitHandler,
    ReagentInventoryManager,
    RealTimeDataAnalyzer,
    RoboticArmIntegration,
    SampleTracker,
    SocialMediaMonitor,
    SpectroscopyAnalyzer,
    ToolChainBuilder,
    ToolDiscoveryAgent,
    ToolPerformanceMonitor,
    UsageAnalytics,
    WebMonitoringAgent,
    # Browser Agent
    WebScraper,
    WebsiteNavigator,
    get_lab_controller,
    get_mcp_manager,
    get_robotic_arm,
    get_sample_tracker,
    get_web_scraper,
)

__all__ = [
    # Lab Automation
    "LabEquipmentController",
    "RoboticArmIntegration",
    "AutomatedPipetting",
    "SampleTracker",
    "EnvironmentalMonitor",
    "ExperimentScheduler",
    "QualityControlAgent",
    "ReagentInventoryManager",
    "ProtocolVersionControl",
    "ExperimentLogger",
    "AnomalyDetector",
    "RealTimeDataAnalyzer",
    "BayesianOptimizer",
    # Browser Agent
    "WebScraper",
    "FormAutoFiller",
    "WebMonitoringAgent",
    "PDFDownloader",
    # MCP
    "MCPServerManager",
    "ToolChainBuilder",
    "APIGateway",
    # Factory functions
    "get_lab_controller",
    "get_robotic_arm",
    "get_sample_tracker",
    "get_web_scraper",
    "get_mcp_manager",
]
