"""JARVIS Advanced Features Module Exports"""
from .features import (
    # Analytics
    MetaAnalysisBot,
    SystematicReviewAgent,
    NetworkMetaAnalysis,
    BayesianStatsEngine,
    CausalInferenceAgent,
    TimeSeriesAnalyzer,
    SurvivalAnalysisBot,
    MissingDataHandler,
    PowerAnalysisCalculator,
    EffectSizeEstimator,
    PublicationBiasDetector,
    HeterogeneityAnalyzer,
    SensitivityAnalysisBot,
    SubgroupAnalyzer,
    RegressionWizard,
    MLPipelineBuilder,
    FeatureSelectionAgent,
    ModelComparisonTool,
    CrossValidationManager,
    ExplainableAIReporter,
    # Visualization
    MoleculeViewer3D,
    PathwayMapBuilder,
    ChromosomeBrowser,
    PhylogeneticTreeViewer,
    AdvancedHeatmapGenerator,
    VolcanoPlotBuilder,
    ManhattanPlotGenerator,
    DimensionReductionVisualizer,
    NetworkGraphBuilder,
    CircosPlotGenerator,
    # Security
    HIPAAComplianceChecker,
    GDPRDataHandler,
    DataAnonymizer,
    AuditTrailManager,
    AccessControlManager,
    EncryptionManager,
    # Mobile
    MobileAppConfig,
    WatchIntegration,
    SiriShortcuts,
    GoogleAssistant,
    OfflineModePro,
    BackgroundSync,
    PushNotificationsPro,
    # Enterprise
    TeamWorkspace,
    RoleBasedAccess,
    ProjectTemplates,
    ResourceSharing,
    ActivityFeed,
    MentionsComments,
    RealTimeCollaboration,
    VersionHistory,
    # Factory functions
    get_meta_analysis,
    get_systematic_review,
    get_hipaa_checker,
    get_team_workspace,
)

__all__ = [
    # Analytics
    "MetaAnalysisBot",
    "SystematicReviewAgent",
    "BayesianStatsEngine",
    "CausalInferenceAgent",
    "TimeSeriesAnalyzer",
    "SurvivalAnalysisBot",
    "PowerAnalysisCalculator",
    # Visualization
    "MoleculeViewer3D",
    "PathwayMapBuilder",
    "VolcanoPlotBuilder",
    "NetworkGraphBuilder",
    # Security
    "HIPAAComplianceChecker",
    "GDPRDataHandler",
    "DataAnonymizer",
    "AuditTrailManager",
    # Enterprise
    "TeamWorkspace",
    "RoleBasedAccess",
    "ActivityFeed",
    # Factory
    "get_meta_analysis",
    "get_systematic_review",
    "get_hipaa_checker",
    "get_team_workspace",
]
