"""BibTeX exporter for academic reference management.

This module provides:
- export_bibtex(): Export references to BibTeX format

Per RP15, this enables direct import into LaTeX/Overleaf/Zotero.
"""

from __future__ import annotations

import re

from .reference import Reference


def _sanitize_key(s: str) -> str:
    """Sanitize string for BibTeX citation key."""
    # Remove special characters, keep alphanumeric and underscore
    key = re.sub(r"[^a-zA-Z0-9_]", "", s)
    return key[:30] if key else "ref"


def _escape_bibtex(s: str) -> str:
    """Escape special characters for BibTeX."""
    if not s:
        return ""
    # Escape special LaTeX characters
    replacements = [
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]
    result = s
    for old, new in replacements:
        result = result.replace(old, new)
    return result


def format_bibtex_entry(ref: Reference) -> str:
    """Format a single reference as BibTeX entry.

    Uses @misc type as a safe default for all source types.

    Args:
        ref: The reference to format.

    Returns:
        BibTeX entry string.
    """
    # Generate citation key
    base_key = ref.title or ref.get_display_locator()
    key = _sanitize_key(base_key) or f"ref{ref.id}"

    lines = [f"@misc{{{key},"]

    # Title
    title = ref.title or ref.get_display_locator()
    lines.append(f"  title        = {{{_escape_bibtex(title)}}},")

    # Authors
    if ref.authors:
        author_str = " and ".join(ref.authors)
        lines.append(f"  author       = {{{_escape_bibtex(author_str)}}},")

    # Year
    if ref.year:
        lines.append(f"  year         = {{{ref.year}}},")

    # Source type as howpublished
    if ref.source_type == "pdf":
        lines.append("  howpublished = {PDF},")
    elif ref.source_type == "url":
        url = ref.get_display_locator()
        lines.append(f"  howpublished = {{\\url{{{url}}}}},")
        lines.append(f"  url          = {{{url}}},")
    else:
        lines.append("  howpublished = {Local file},")

    # Pages as note
    pages_str = ref.get_pages_display()
    if pages_str:
        # Convert "pp. 1-3" to LaTeX format "pp. 1--3"
        pages_latex = pages_str.replace("-", "--")
        lines.append(f"  note         = {{{pages_latex}}},")

    # Accessed date
    accessed = ref.accessed_at.strftime("%Y-%m-%d")
    lines.append(f"  note         = {{Accessed: {accessed}}},")

    lines.append("}")

    return "\n".join(lines)


def export_bibtex(refs: list[Reference]) -> str:
    """Export references to BibTeX format.

    Args:
        refs: List of references to export.

    Returns:
        Complete BibTeX file content.
    """
    if not refs:
        return "% No references\n"

    header = [
        "% BibTeX references",
        "% Generated by Jarvis Evidence QA",
        f"% Total references: {len(refs)}",
        "",
    ]

    entries = [format_bibtex_entry(ref) for ref in refs]

    return "\n".join(header) + "\n".join(entries) + "\n"
